import React, { useState } from "react";
import {
  Leaf,
  Recycle,
  Wind,
  Droplet,
  Sun,
  TreePine,
  Lightbulb,
  Target,
  Users,
  TrendingUp,
  BookOpen,
  Heart,
  Globe,
  Zap,
  Sprout,
  ChevronRight,
} from "lucide-react";

const FlashCard = ({ icon: Icon, title, frontContent, backContent, color }) => {
  const [isFlipped, setIsFlipped] = useState(false);

  return (
    <div
      className="relative h-80 cursor-pointer perspective-1000"
      onClick={() => setIsFlipped(!isFlipped)}
    >
      <div
        className={`relative w-full h-full transition-transform duration-700 transform-style-3d ${
          isFlipped ? "rotate-y-180" : ""
        }`}
      >
        {/* Front of card */}
        <div
          className={`absolute w-full h-full backface-hidden glass p-8 rounded-3xl border ${color} shadow-2xl hover:shadow-3xl transition-all`}
        >
          <div className="flex flex-col items-center justify-center h-full text-center">
            <div className={`w-20 h-20 bg-gradient-to-br ${color} rounded-3xl flex items-center justify-center mb-6 shadow-xl`}>
              <Icon className="w-10 h-10 text-white" />
            </div>
            <h3 className="text-3xl font-black text-gray-900 mb-4">{title}</h3>
            <p className="text-lg text-gray-600 leading-relaxed">{frontContent}</p>
            <div className="mt-6 text-sm font-bold text-gray-500 flex items-center gap-2">
              <span>Click to flip</span>
              <ChevronRight className="w-4 h-4" />
            </div>
          </div>
        </div>

        {/* Back of card */}
        <div
          className={`absolute w-full h-full backface-hidden glass p-8 rounded-3xl border ${color} shadow-2xl rotate-y-180`}
        >
          <div className="flex flex-col justify-center h-full">
            <h4 className="text-2xl font-bold text-gray-900 mb-4">{title}</h4>
            <p className="text-base text-gray-700 leading-relaxed">{backContent}</p>
            <div className="mt-6 text-sm font-bold text-gray-500 flex items-center gap-2">
              <span>Click to flip back</span>
              <ChevronRight className="w-4 h-4 rotate-180" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const About = ({ user, onNavigateToScanner }) => {
  const handleGetStarted = () => {
    // If user is logged in, go to scanner page
    // If not logged in, this will be handled by parent component
    if (user) {
      onNavigateToScanner();
    } else {
      // User not logged in - parent should handle showing login
      onNavigateToScanner();
    }
  };

  const flashCards = [
    {
      icon: Leaf,
      title: "Sustainability",
      frontContent: "What does it mean to live sustainably?",
      backContent:
        "Sustainability means meeting our present needs without compromising the ability of future generations to meet their own needs. It involves balancing environmental, social, and economic factors to create a healthier planet. Simple actions like reducing waste, conserving energy, and choosing eco-friendly products make a big difference.",
      color: "from-green-500 to-emerald-600",
    },
    {
      icon: Wind,
      title: "Carbon Footprint",
      frontContent: "How do our daily choices impact the planet?",
      backContent:
        "A carbon footprint is the total amount of greenhouse gases (especially CO₂) generated by our actions. Everything from driving a car to buying packaged food contributes to it. By measuring and reducing our carbon footprint through conscious choices, we can significantly slow climate change and protect ecosystems.",
      color: "from-blue-500 to-cyan-600",
    },
    {
      icon: Recycle,
      title: "Eco-Friendly Products",
      frontContent: "What makes a product truly eco-friendly?",
      backContent:
        "Eco-friendly products are made with minimal environmental impact. They use sustainable materials, have reduced packaging, are biodegradable or recyclable, and are produced with renewable energy. Look for certifications like Fair Trade, USDA Organic, or Carbon Neutral to identify genuine eco-friendly products.",
      color: "from-teal-500 to-green-600",
    },
    {
      icon: Sun,
      title: "Renewable Energy",
      frontContent: "Why is renewable energy crucial for our future?",
      backContent:
        "Renewable energy comes from natural sources like sunlight, wind, and water that replenish themselves. Unlike fossil fuels, they don't produce harmful emissions. Transitioning to solar, wind, and hydro power reduces greenhouse gases, fights climate change, and creates a sustainable energy future for all.",
      color: "from-orange-500 to-yellow-500",
    },
    {
      icon: Sprout,
      title: "Circular Economy",
      frontContent: "How can we eliminate waste entirely?",
      backContent:
        "A circular economy keeps resources in use as long as possible through reuse, repair, refurbishment, and recycling. Instead of the traditional 'take-make-dispose' model, it creates a closed-loop system where waste becomes a resource. This approach reduces pollution, conserves materials, and creates sustainable business models.",
      color: "from-purple-500 to-pink-600",
    },
    {
      icon: TreePine,
      title: "Green Living Tips",
      frontContent: "Simple changes for a sustainable lifestyle?",
      backContent:
        "Start with small steps: use reusable bags and bottles, reduce meat consumption, compost organic waste, buy local and seasonal produce, switch to LED bulbs, unplug electronics when not in use, choose public transport or bike, and support sustainable brands. Every action counts!",
      color: "from-emerald-500 to-teal-600",
    },
  ];

  const howItWorks = [
    {
      step: "1",
      icon: Zap,
      title: "Scan or Describe",
      description: "Upload a barcode, product image, or simply describe the product you want to analyze.",
    },
    {
      step: "2",
      icon: Lightbulb,
      title: "AI Analysis",
      description: "Our GPT-4o powered engine analyzes ingredients, materials, and environmental impact in real-time.",
    },
    {
      step: "3",
      icon: TrendingUp,
      title: "Get Insights",
      description: "Receive detailed eco-scores, carbon footprint data, and personalized recommendations instantly.",
    },
  ];

  const impactStats = [
    { value: "95%", label: "Accuracy Rate", icon: Target },
    { value: "10K+", label: "Products Analyzed", icon: BookOpen },
    { value: "2.5T", label: "CO₂ Data Points", icon: Globe },
    { value: "1K+", label: "Active Users", icon: Users },
  ];

  return (
    <div className="space-y-20 py-8">
      {/* Mission Statement */}
      <section className="text-center max-w-5xl mx-auto glass p-12 rounded-4xl border border-green-100/30 shadow-2xl">
        <div className="flex justify-center mb-8">
          <div className="w-20 h-20 bg-gradient-to-r from-green-500 to-emerald-600 rounded-3xl flex items-center justify-center shadow-xl">
            <Heart className="w-10 h-10 text-white" />
          </div>
        </div>
        <h1 className="text-5xl md:text-6xl font-black mb-6 bg-gradient-to-r from-gray-900 to-emerald-900 bg-clip-text text-transparent">
          Our Mission
        </h1>
        <p className="text-2xl text-gray-600 leading-relaxed font-light">
          Empowering consumers to make{" "}
          <span className="font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
            informed, sustainable choices
          </span>{" "}
          through cutting-edge AI technology. We believe every purchase is a vote for the kind of world we want to live in.
        </p>
      </section>

      {/* How It Works */}
      <section className="max-w-7xl mx-auto">
        <h2 className="text-5xl md:text-6xl font-black text-center text-gray-900 mb-16 bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text">
          How It Works
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {howItWorks.map((item, idx) => (
            <div
              key={idx}
              className="glass p-10 rounded-3xl hover:-translate-y-4 hover:shadow-3xl transition-all duration-500 border border-green-100/30 group relative"
            >
              <div className="absolute -top-6 -left-6 w-16 h-16 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center text-3xl font-black text-white shadow-2xl">
                {item.step}
              </div>
              <div className="w-20 h-20 bg-gradient-to-br from-green-500 via-emerald-500 to-teal-500 rounded-3xl flex items-center justify-center mb-8 shadow-2xl group-hover:scale-110 transition-all duration-500 mx-auto mt-4">
                <item.icon className="w-10 h-10 text-white" />
              </div>
              <h3 className="text-3xl font-bold text-gray-900 mb-4 text-center group-hover:text-green-600 transition-colors">
                {item.title}
              </h3>
              <p className="text-lg text-gray-600 leading-relaxed text-center">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Educational Flashcards */}
      <section className="max-w-7xl mx-auto">
        <h2 className="text-5xl md:text-6xl font-black text-center text-gray-900 mb-6 bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text">
          Learn About Sustainability
        </h2>
        <p className="text-xl text-center text-gray-600 mb-16 max-w-3xl mx-auto">
          Click on each card to discover essential knowledge about eco-friendly living and environmental impact
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {flashCards.map((card, idx) => (
            <FlashCard
              key={idx}
              icon={card.icon}
              title={card.title}
              frontContent={card.frontContent}
              backContent={card.backContent}
              color={card.color}
            />
          ))}
        </div>
      </section>

      {/* Impact Statistics */}
      <section className="max-w-7xl mx-auto glass p-12 rounded-4xl border border-green-100/30 shadow-2xl">
        <h2 className="text-5xl md:text-6xl font-black text-center text-gray-900 mb-16 bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text">
          Our Impact
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {impactStats.map((stat, idx) => (
            <div key={idx} className="text-center group">
              <div className="w-16 h-16 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center mb-4 shadow-xl group-hover:scale-110 transition-all mx-auto">
                <stat.icon className="w-8 h-8 text-white" />
              </div>
              <div className="text-4xl md:text-5xl font-black bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent mb-3">
                {stat.value}
              </div>
              <div className="text-lg font-bold text-gray-700 uppercase tracking-wider">
                {stat.label}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Call to Action */}
      <section className="text-center max-w-5xl mx-auto glass p-12 rounded-4xl border border-green-100/30 shadow-2xl bg-gradient-to-br from-green-50 to-emerald-50">
        <h2 className="text-4xl md:text-5xl font-black text-gray-900 mb-6">
          Join the Green Revolution
        </h2>
        <p className="text-xl text-gray-600 mb-8 leading-relaxed">
          Start making sustainable choices today. Every scan brings us closer to a healthier planet.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <button 
            onClick={handleGetStarted}
            className="glass bg-gradient-to-r from-green-500 to-emerald-600 text-white px-12 py-6 rounded-3xl text-xl font-black shadow-2xl hover:shadow-3xl hover:-translate-y-2 transition-all flex items-center gap-3 justify-center cursor-pointer"
          >
            <Leaf className="w-6 h-6" />
            Get Started Now
          </button>
          <button className="glass bg-white text-gray-900 px-12 py-6 rounded-3xl text-xl font-black shadow-2xl hover:shadow-3xl hover:-translate-y-2 transition-all border-2 border-green-200 flex items-center gap-3 justify-center">
            <BookOpen className="w-6 h-6" />
            Learn More
          </button>
        </div>
      </section>
    </div>
  );
};

export default About;
